version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 socket
    environment:
      - DISPLAY
    ports:
      - "3000:3000"
    depends_on:
      - backend
